# Generated by Django 3.0.3 on 2021-06-09 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admit_date', models.DateField(auto_now_add=True, verbose_name='Admit Date')),
                ('symptomps', models.TextField()),
                ('department', models.CharField(choices=[('CL', 'Cardiologist'), ('DL', 'Dermatologists'), ('EMC', 'Emergency Medicine Specialists'), ('IL', 'Immunologists'), ('AL', 'Anesthesiologists'), ('CRS', 'Colon and Rectal Surgeons')], default='CL', max_length=3)),
                ('release_date', models.DateField(auto_now_add=True, verbose_name='Release Date')),
                ('assigned_doctor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='doctor.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patient.patient')),
            ],
        ),
    ]
