# Generated by Django 3.0.3 on 2021-06-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20210613_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
