# Generated by Django 3.0.3 on 2021-06-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20210629_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_history',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Release Date'),
        ),
    ]
