# Generated by Django 3.0.3 on 2021-06-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_auto_20210630_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_cost',
            old_name='Other_charge',
            new_name='other_charge',
        ),
    ]
