# Generated by Django 3.0.3 on 2021-07-05 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_auto_20210705_0621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appontment_date',
            new_name='appointment_date',
        ),
    ]
