# Generated by Django 3.0.3 on 2021-07-07 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_doctor_status'),
        ('patient', '0015_remove_patient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_history',
            name='assigned_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
        ),
    ]
